# Project information
site_name: Paper Prowler
site_url: https://davidberenstein1957.github.io/paper-prowler
site_author: davidberenstein1957
site_description: A website by davidberenstein1957 that keeps track of papers and interesting content.
copyright: Copyright &copy; 2017 - 2024 davidberenstein1957

# Repository
repo_name: davidberenstein1957/paper-prowler
repo_url: https://github.com/davidberenstein1957/paper-prowler
edit_uri: edit/main/docs/

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/david-berenstein-1bab11105
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/davidbstein1957

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - navigation.path
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      primary: white
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

watch:
  - src/paper_prowler

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # activating permalink: true makes the anchor link works in the notebooks
  - toc:
      permalink: true


plugins:
  - search
  - open-in-new-tab
  - gen-files:
      scripts:
        - docs/scripts/prowl_arxiv.py
        #- docs/scripts/prowl_rss.py
        #- docs/scripts/create_rss_pages.py
        - docs/scripts/create_arxiv_pages.py
  - section-index
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          selection:
            inherited_members: true # Allow looking up inherited methods
          rendering:
            show_root_heading: true # actually display anything at all...
            # show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: false # don't include source code
            members_order: source # order methods according to their order of definition in the source code, not alphabetical order
            heading_level: 4
            # hide private members
            private: true
  - social
  - mknotebooks